### PR TITLE
Simplify the markdown in the things as much as possible

### PR DESCRIPTION
**Pull request by tom-h**
This PR stirs things up a little. It makes the Markdown file as simple as possible, and pushes all the complexity into both the front matter and a special layout file.

The idea is that the thing file should be really simple and focus only on the relevant content. All the stuff on top is moved out of the file (navigation between things, getting help or credit for doing the thing...even the "number" of the thing).

Some content is moved to front matter so it can be auto-magicked into other stuff. The title and initial description and the overview of the thing are all moved into front matter. A "thing number" is added as well to create the order in which it occurs in the things.

One final thing I've done is to move towards a semantically meaningful naming structure:

/researchdata/things: all the things
/researchdata/thing-1: the first thing

This is anticipating that we might want:

/health_and_medical/things
/health_and_medical/thing-1 etc.

Still thinking about the best way to do this as content is regularly duplicated between the collections of things.

You can preview what this PR would do to the display of the things by going here:
https://tom-h.github.io/ARDC-23-things/researchdata/things

And have a look at the simplified markdown here:
https://raw.githubusercontent.com/tom-h/ARDC-23-things/gh-pages/_things/thing-1.md

Oh, there are some quirks of github pages that don't happen on my local setup... but I'm kinda fed up at this point and anyway, you may not like this change.
- sorting by integer doesn't look like it's working. This means the things listing doesn't work.
- setting page defaults doesn't work... so I have to add a layout to the front matter of the things

### CODE REVIEW

**Comment by tom-h** [comment]
One consequence of this layout is that the prompts for connecting/getting help and the navigation forwards are at the end of each thing, rather than repeated throughout. I can't currently work out a way within jekyll to insert material into the content (without using the obvious "include" method, and thus making the markdown a little more complex again). I guess we could solve this with a bit of javascript... but that's a bit of a hack.

**Comment by NicholaBurton** [comment]
Overall I like this - it looks very clean, but still allows us to change repeated content easily. 

> One consequence of this layout is that the prompts for connecting/getting help and the navigation forwards are at the end of each thing, rather than repeated throughout. 

I actually don't mind that, tbh. I found the repetition of having this stuff at the end of each section within the Thing looked a little odd if the sections weren't particularly long, and I think my instinct would be to scroll to the bottom of the page anyway.

Is there a way to recreate the little curated collections of Things that used to be at the bottom of most Things in this setup? Is that something that we want to retain?

**Comment by mpfl** [comment]
You're saving me a lot of work, Tom! I was planning to mess around with this after getting the HTML template.

I like this layout. I think we could get away with putting the help text at the top and bottom of the page. It might look a little clumsy, but it would keep the thing-*.md files cleaner.

It would be nice to get a numerical sort rather than an alpha sort - I wonder if that can be configured somewhere.

**Comment by tom-h** [comment]
> Is there a way to recreate the little curated collections of Things that used to be at the bottom of most Things in this setup? Is that something that we want to retain?

Yes! And I've started to do it. That is why there's a "category" in (most of) the front matter. The format appeared to be that all the things in the same category were listed at the bottom, and, if it was the last thing in the category, to list all of the next category as well. I just need to modify the layout to include this.

**Comment by tom-h** [comment]
> You're saving me a lot of work, Tom! I was planning to mess around with this after getting the HTML template.

I'm having fun learning Jekyll :-)

> It would be nice to get a numerical sort rather than an alpha sort - I wonder if that can be configured somewhere.

Yeah, it's there in the _config.yml but it's not working for some reason... works on my local machine just fine.

**Comment by tom-h** [comment]
I'm rather fond of a sidebar layout like this one:

https://fongandrew.github.io/hydeout/

That way the help and things navigation can all happen there. This one reverts to a header on a mobile FYI. But I gather you're getting a template from comms that determines the look and feel right @mpfl ? If so I won't continue to muck about with the look.

**Comment by mpfl** [comment]
The template won't be terribly sophisticated - it will essentially be just a header and a footer for us to wrap content with.

**Comment by mpfl** [comment]
Nobody said no, so let's merge this!

**Pull request merged**
