### PR TITLE
incorporate several includes for toc, headings, and getting help

### PR DESCRIPTION
**Pull request by tom-h**
@mpfl for your consideration. This PR breaks out a number of repeated elements to make them easier to be consistent across the things, but also easier to update. It also updates the front matter.

1. add an _includes directory:
 for the templates :-)
2. add _includes/get-help.md:
 Standard "get help" text. It could be modified to add the credly badges  back in later if you like. This text gets repeated so often this is a no brainer.
3. add toc.md:
 A table of contents. This adds nav links to the toc and expects a little blurb for each section. This might need to be modified to handle some of the weirder things.
4. add start.md, learn.md, challenge.md:
 These are little bits of template to standardise the sections. This bit is less necessary, but it does help to ensure that the same styling/conventions apply across each document. Up you whether you keep this.
5. Lots of changes to front matter:
 a. tidy the description, including identifying the thing within it
 b. remove unnecessary elements (many of which could be specified in the config file, if even relevant).
 c. add a 'thing' variable to be used for all sorts of things (a navigation PR is coming that uses this)
 d. update the author
 e. capture the categories that each thing falls under. My intention is to add a little template for the related sections at the end of the document using this metadata.
6. remove the title from the content
 This should be specified in the front matter, and then exposed in the document template 

Merge whatever parts of this suit you.

### CODE REVIEW

**Comment by mpfl** [comment]
This one is tricky, and I welcome feedback from the wider group on this.

I personally like to use features like this to reduce my workload, but I'm concerned that by using them, we make the material a little less accessible (and available for reuse by) people who aren't quite as comfortable with Markdown/Jekyll/Github as we are.

@rowan-ardc @ragamouf @NicholaBurton @klevetate What do you think?

**Comment by NicholaBurton** [comment]
Hmm, I share your concern @mpfl - even though I think what is actually being done here is pretty straightforward (and nifty!), I think there's a risk that it pushes the appearance of the markdown from "text formatting" to "code", and I've met plenty of people who would be perfectly happy to learn some new text formatting rules but would be intimidated by "code"... Depends who the anticipated re-user is?

Who do we envisage re-using this, and what do we expect them to be experienced/comfortable with?

**Comment by tom-h** [comment]
Ah, okay, fair enough. I think a hybrid approach might be sensible. As much as possible the content should be clear and readable markdown, and all the bells and whistles should be achieved in front matter and layouts. Let me have another crack at it, and I'll submit another PR.

**Comment by tom-h** [comment]
Okay, so I'm closing this PR and moving the activity over to PR https://github.com/au-research/ARDC-23-things/pull/48

**Pull request closed without merging**
