### PR TITLE
update content for Thing 11 and 13

### PR DESCRIPTION
**Pull request by klevetate**
I think I'm doing this right...

### CODE REVIEW

**Comment by klevetate** [comment]
I forgot to add the Slack chanel bit at the end... do I still need to do that, or has @tom-h automagicked that bit too?

**Comment by tom-h** [comment]
@klevetate Start a branch in your fork and copy your edits for thing 13 into it. I will review and merge this PR but only accept changes to thing 11.

**Comment by tom-h** [comment]
I have submitted a PR to @klevetate 's fork to resolve these conflicts. Waiting for Kerry to merge this and then I suggest we simply review all changes to thing 11 and 13 and merge here.

**Comment by klevetate** [comment]
@tom-h I've merged your pull request in my fork (apologies for the tardiness)

**Comment by tom-h** [comment]
Don't forget to branch in your fork next time :-)

**Pull request merged**
